title: Manas Jani # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with strong analytical skills and expertise in data analysis tools.  
  <br><br>
  Seeking a role to apply my skills in extracting insights from complex datasets, creating reports, and providing actionable recommendations for informed decision-making within a dynamic team. 
  <br><br>
  <a href="https://www.linkedin.com/in/manas-jani/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-H8BFJ6XEH0 # your Google Analytics tracking ID here
